---
- name: Prepare the node.
  hosts: renumber

  vars_files:
    - vars/main.yml
    - vars/setup.yml

  roles:
    - role: setup
      become: true

- name: Setup renumber service.
  hosts: renumber

  vars_files:
    - vars/main.yml

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup renumber service.
      import_tasks: tasks/flask.yml
