---
- name: Ensure required packages are installed.
  ansible.builtin.package:
    name: 
      # we need gawk because mawk is unbelievably slow for our workload
      - gawk
      # using virtual env because python3-flask is too outdated
      - python3-pip
      - virtualenv
    state: present
  become: true

- name: Ensure flask user is created.
  ansible.builtin.user:
    name: flask
    create_home: false
    system: true
    shell: /usr/sbin/nologin
    state: present
  become: true

- name: Ensure the app directory exists.
  ansible.builtin.file:
    path: /opt/renumber
    state: directory
    owner: flask
    group: flask
    mode: '0755'
  become: true

- name: Ensure the app is copied.
  ansible.builtin.copy:
    src: app/
    dest: /opt/renumber/
    owner: flask
    group: flask
  notify:
    - restart app
  become: true

- name: Ensure app service is copied.
  ansible.builtin.template:
    src: templates/renumber.service.j2
    dest: /etc/systemd/system/renumber.service
    mode: '0644'
  notify:
    - systemctl daemon-reload
    - restart app
  become: true

- name: Ensure virtualenv with correct dependencies is created.
  ansible.builtin.pip:
    requirements: /opt/renumber/requirements.txt
    virtualenv: /opt/renumber/venv
  become: true
  # the service is owned by the flask user so we should also do the
  # virtualenv as flask
  become_user: flask

- name: Flush handlers.
  meta: flush_handlers

- name: Ensure app service is enabled and started.
  ansible.builtin.service:
    name: renumber
    enabled: true
    state: started
  become: true
