---
- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  
- name: restart app
  ansible.builtin.service:
    name: renumber
    state: restarted
  become: true
